version: '3.3'

services:
  app:
    container_name: 'node-app-2'
    build: .
    volumes:
      - .:/node-app-2
      - node_modules:/app/node_modules
    ports:
      - 5200:5200
    stdin_open: true
    environment: 
      - PORT=5200
    command: npm start
volumes:
  node_modules: